FROM python:3.12.9

COPY . /app
WORKDIR /app

# RUN pip install --no-cache-dir --upgrade -e .
RUN pip install --no-cache-dir --upgrade -r ./server/requirements.txt

CMD ["python", "-m", "fastapi", "run", "./server/main.py", "--host", "0.0.0.0", "--port", "8000"]
