FROM python:3.12.9

WORKDIR /app

COPY server/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY server/ ./server

EXPOSE 8000

CMD ["fastapi", "run", "server/main.py", "--port", "8000"]